language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aswilson444/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aswilson444/docker-react npm run test
